/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/signup": {
    post: operations["AuthController_signup"];
  };
  "/auth/verify-email": {
    get: operations["AuthController_verifyEmail"];
  };
  "/auth/login": {
    post: operations["AuthController_login"];
  };
  "/auth/forgot-password": {
    post: operations["AuthController_forgotPassword"];
  };
  "/auth/reset-password": {
    post: operations["AuthController_resetPassword"];
  };
  "/auth/logout": {
    post: operations["AuthController_logout"];
  };
  "/auth/refresh-token": {
    post: operations["AuthController_refreshToken"];
  };
  "/auth/me": {
    get: operations["AuthController_getMe"];
  };
  "/auth/resend-verification": {
    post: operations["AuthController_resendVerification"];
  };
  "/users/me": {
    get: operations["UserController_me"];
    put: operations["UserController_updateProfile"];
  };
  "/users/{id}": {
    get: operations["UserController_getUser"];
  };
  "/users/me/change-password": {
    put: operations["UserController_changePassword"];
  };
  "/onboarding/initialize": {
    post: operations["OnboardingController_initializeOnboarding"];
  };
  "/onboarding/step1": {
    post: operations["OnboardingController_submitStep1"];
  };
  "/onboarding/step2": {
    post: operations["OnboardingController_submitStep2"];
  };
  "/onboarding/complete": {
    post: operations["OnboardingController_completeOnboarding"];
  };
  "/onboarding/status": {
    get: operations["OnboardingController_getOnboardingStatus"];
  };
  "/blood-requests": {
    post: operations["BloodRequestController_createBloodRequest"];
  };
  "/blood-requests/active": {
    get: operations["BloodRequestController_getActiveRequests"];
  };
  "/blood-requests/all": {
    get: operations["BloodRequestController_getAllRequests"];
  };
  "/blood-requests/my": {
    get: operations["BloodRequestController_getMyRequests"];
  };
  "/blood-requests/donor": {
    get: operations["BloodRequestController_getRequestsForDonor"];
  };
  "/blood-requests/{requestId}": {
    get: operations["BloodRequestController_getRequestById"];
  };
  "/blood-requests/{requestId}/accept": {
    post: operations["BloodRequestController_acceptBloodRequest"];
  };
  "/blood-requests/{requestId}/confirm": {
    post: operations["BloodRequestController_confirmDonation"];
  };
  "/blood-requests/{requestId}/arrival-alert": {
    post: operations["BloodRequestController_notifyDonorArrival"];
  };
  "/blood-requests/{requestId}/escalate": {
    post: operations["BloodRequestController_escalateRequest"];
  };
  "/blood-requests/{requestId}/update": {
    post: operations["BloodRequestController_updateBloodRequest"];
  };
  "/blood-requests/{requestId}/cancel": {
    post: operations["BloodRequestController_cancelBloodRequest"];
  };
  "/notifications/preferences": {
    /** Get user notification settings */
    get: operations["NotificationController_getPreferences"];
    /** Update notification preferences */
    put: operations["NotificationController_updatePreferences"];
  };
  "/notifications": {
    /** Get user's notification history (paginated) */
    get: operations["NotificationController_getHistory"];
  };
  "/notifications/{id}/read": {
    /** Mark a specific notification as read */
    put: operations["NotificationController_markRead"];
  };
  "/notifications/read-all": {
    /** Mark all notifications as read */
    put: operations["NotificationController_markAllRead"];
  };
  "/analytics/bridger": {
    get: operations["AnalyticsController_getBridgerAnalytics"];
  };
  "/analytics": {
    get: operations["AnalyticsController_getAnalytics"];
  };
  "/role-upgrades/request": {
    post: operations["RoleUpgradeController_requestRoleUpgrade"];
  };
  "/role-upgrades/pending": {
    get: operations["RoleUpgradeController_getPendingUpgradeRequests"];
  };
  "/role-upgrades/{requestId}/approve": {
    post: operations["RoleUpgradeController_approveRoleUpgrade"];
  };
  "/role-upgrades/{requestId}/reject": {
    post: operations["RoleUpgradeController_rejectRoleUpgrade"];
  };
  "/role-upgrades/my-history": {
    get: operations["RoleUpgradeController_getMyUpgradeHistory"];
  };
  "/donor/dashboard": {
    get: operations["DonorController_getDonorDashboard"];
  };
  "/donor/dashboard/summary": {
    get: operations["DonorController_getDonorDashboardSummary"];
  };
  "/donor/stats": {
    get: operations["DonorController_getDonorStats"];
  };
  "/donor/profile/completion": {
    get: operations["DonorController_getDonorProfileCompletion"];
  };
  "/donor/profile": {
    get: operations["DonorController_getDonorProfile"];
    post: operations["DonorController_updateProfile"];
  };
  "/donor/nearby-requests": {
    get: operations["DonorController_getNearbyBloodRequests"];
  };
  "/donor/blood-request/{requestId}": {
    get: operations["DonorController_getBloodRequestDetails"];
  };
  "/donor/resources": {
    get: operations["DonorController_getResources"];
  };
  "/donor/history": {
    get: operations["DonorController_getDonationHistory"];
  };
  "/donor/history/{donationId}": {
    get: operations["DonorController_getDonationRecord"];
  };
  "/donor/certificate/{donationId}": {
    get: operations["DonorController_getDonationCertificate"];
  };
  "/donor/notification-preferences": {
    get: operations["DonorController_getNotificationPreferences"];
    post: operations["DonorController_updateNotificationPreferences"];
  };
  "/donor/medical-eligibility": {
    get: operations["DonorController_getMedicalEligibility"];
  };
  "/donor/availability": {
    post: operations["DonorController_updateAvailability"];
  };
  "/donor/accept-request": {
    post: operations["DonorController_acceptBloodRequest"];
  };
  "/donor/reject-request": {
    post: operations["DonorController_rejectBloodRequest"];
  };
  "/donor/update-progress": {
    post: operations["DonorController_updateDonationProgress"];
  };
  "/donor/request-progress/{requestId}": {
    get: operations["DonorController_getRequestProgress"];
  };
  "/donor/badges": {
    get: operations["DonorController_getBadges"];
  };
  "/donor/leaderboard": {
    get: operations["DonorController_getLeaderboard"];
  };
  "/donor/settings/anonymity": {
    put: operations["DonorController_toggleAnonymity"];
  };
  "/donor/health-screening/questions": {
    get: operations["DonorController_getHealthScreeningQuestions"];
  };
  "/donor/health-screening/submit": {
    post: operations["DonorController_submitHealthScreening"];
  };
  "/donor/goal": {
    get: operations["DonorController_getGoal"];
    post: operations["DonorController_setGoal"];
  };
  "/donor/shareable-impact": {
    get: operations["DonorController_getShareableImpact"];
  };
  "/donor/activity-feed": {
    get: operations["DonorController_getActivityFeed"];
  };
  "/donor/feedback": {
    post: operations["DonorController_submitDonationFeedback"];
  };
  "/pulse-leader/dashboard": {
    get: operations["PulseLeaderController_getPulseLeaderDashboard"];
  };
  "/pulse-leader/search-donors": {
    post: operations["PulseLeaderController_searchDonors"];
  };
  "/pulse-leader/escalation-history": {
    get: operations["PulseLeaderController_getEscalationHistory"];
  };
  "/pulse-leader/broadcast": {
    post: operations["PulseLeaderController_broadcastMessage"];
  };
  "/pulse-leader/recent-activities": {
    get: operations["PulseLeaderController_getRecentActivities"];
  };
  "/pulse-leader/network-performance": {
    get: operations["PulseLeaderController_getNetworkPerformance"];
  };
  "/pulse-leader/campaigns": {
    get: operations["PulseLeaderController_getCampaigns"];
    post: operations["PulseLeaderController_createCampaign"];
  };
  "/pulse-leader/bridgers": {
    get: operations["PulseLeaderController_getBridgers"];
  };
  "/pulse-leader/bridgers/{bridgerId}": {
    post: operations["PulseLeaderController_addBridgerToOrg"];
  };
  "/inventory": {
    /** Get current blood unit counts per type at user's facility */
    get: operations["InventoryController_getInventory"];
  };
  "/inventory/adjust": {
    /** Submit adjustment (received/used/wastage) with reason */
    post: operations["InventoryController_adjustInventory"];
  };
  "/inventory/history": {
    /** Adjustment history (paginated) */
    get: operations["InventoryController_getInventoryHistory"];
  };
  "/inventory/audit": {
    /** Inventory adjustment audit trail */
    get: operations["InventoryController_getInventoryAudit"];
  };
  "/inventory/transfer": {
    /** Transfer units between facilities */
    post: operations["InventoryController_transferInventory"];
  };
  "/inventory/transfer-history": {
    /** Transfer history */
    get: operations["InventoryController_getTransferHistory"];
  };
  "/appointments": {
    /** Get my appointments */
    get: operations["AppointmentController_getMyAppointments"];
    /** Book a donation appointment */
    post: operations["AppointmentController_bookAppointment"];
  };
  "/appointments/{id}/reschedule": {
    /** Reschedule an appointment */
    put: operations["AppointmentController_rescheduleAppointment"];
  };
  "/appointments/{id}": {
    /** Cancel an appointment */
    delete: operations["AppointmentController_cancelAppointment"];
  };
  "/bridger/dashboard/stats": {
    /** Get Bridger dashboard statistics */
    get: operations["BridgerController_getDashboardStats"];
  };
  "/bridger/donors": {
    /** Search for available donors */
    get: operations["BridgerController_searchDonors"];
  };
  "/bridger/appointments": {
    /** Get facility appointments */
    get: operations["BridgerController_getAppointments"];
  };
  "/bridger/emergency-alert": {
    /** Send emergency push notification to donors */
    post: operations["BridgerController_sendEmergencyAlert"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignupDto: {
      /** @example John Doe */
      fullName: string;
      /**
       * @example Male
       * @enum {string}
       */
      gender: "Male" | "Female" | "Other";
      /** @example +2348012345678 */
      phoneNumber: string;
      /**
       * Format: email
       * @example john@example.com
       */
      email: string;
      /** @example Pass123!@# */
      password: string;
      /** @example Pass123!@# */
      confirmPassword: string;
      /**
       * @example O+
       * @enum {string}
       */
      bloodGroup?: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      /**
       * @example AA
       * @enum {string}
       */
      genotype?: "AA" | "AS" | "SS" | "AC" | "SC";
      /** @example Lagos, Nigeria */
      location?: string;
      /** @example 123 Street Name */
      address?: string;
      /** @example Lagos */
      city?: string;
      /** @example Lagos State */
      state?: string;
      /** @example Nigeria */
      country?: string;
      /** @example 2023-10-01 */
      lastDonationDate?: string;
    };
    LoginDto: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example password123 */
      password: string;
    };
    ForgotPasswordDto: {
      /** Format: email */
      email: string;
    };
    ResetPasswordDto: {
      token: string;
      newPassword: string;
      confirmPassword: string;
    };
    RefreshTokenDto: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      refreshToken: string;
    };
    ResendVerificationDto: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
    };
    UpdateUserProfileDto: {
      fullName?: string;
      phoneNumber?: string;
      location?: string;
      /** @enum {string} */
      bloodGroup?: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      genotype?: string;
    };
    ChangePasswordDto: {
      oldPassword: string;
      newPassword: string;
    };
    OnboardingStep1Dto: {
      /** @example John Doe */
      fullName: string;
      /** @example Male */
      gender: string;
      /** @example +2348012345678 */
      phoneNumber: string;
    };
    OnboardingStep2Dto: {
      /**
       * Format: email
       * @example john@example.com
       */
      email: string;
      /**
       * @example A+
       * @enum {string}
       */
      bloodGroup: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      /**
       * @example AA
       * @enum {string}
       */
      genotype?: "AA" | "AS" | "SS" | "AC" | "SC";
      /** @example Lagos, Nigeria */
      location: string;
      /** @example 2024-01-01 */
      lastDonationDate?: string;
    };
    CompleteOnboardingDto: {
      /** @example password123 */
      password: string;
      /** @example password123 */
      confirmPassword: string;
    };
    CreateBloodRequestDto: {
      /**
       * @example A+
       * @enum {string}
       */
      bloodType: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      /**
       * @example URGENT
       * @enum {string}
       */
      priorityLevel: "CRITICAL" | "URGENT" | "SCHEDULED";
      /** @example 2 */
      unitsNeeded: number;
      /** @example +2348012345678 */
      contactPhone: string;
      /** @example Patient needs blood for surgery */
      additionalNotes?: string;
      patientCondition?: string;
      requiredByDate?: string;
    };
    UpdateBloodRequestDto: {
      /**
       * @example URGENT
       * @enum {string}
       */
      priorityLevel?: "CRITICAL" | "URGENT" | "SCHEDULED";
      /** @example 3 */
      unitsNeeded?: number;
      /** @example +2348012345678 */
      contactPhone?: string;
      /** @example Updated patient notes */
      additionalNotes?: string;
      /**
       * @example PENDING
       * @enum {string}
       */
      status?: "PENDING" | "CONFIRMED" | "FULFILLED" | "CANCELLED" | "IN_PROGRESS" | "EXPIRED";
    };
    UpdateNotificationPreferencesDto: {
      emergencyAlerts?: boolean;
      donationReminders?: boolean;
      communityUpdates?: boolean;
      emailEnabled?: boolean;
      smsEnabled?: boolean;
      pushEnabled?: boolean;
    };
    ProfileCompletion: {
      /** @example 80 */
      percentComplete: number;
      /**
       * @example [
       *   "fullName",
       *   "email"
       * ]
       */
      completedFields: string[];
      /**
       * @example [
       *   "genotype"
       * ]
       */
      remainingFields: string[];
    };
    DonorStatus: {
      /** @example true */
      isAvailable: boolean;
      /** @example A+ */
      bloodGroup: string;
      /**
       * Format: date-time
       * @example 2024-04-01
       */
      nextEligibilityDate: string;
      /**
       * Format: date-time
       * @example 2024-01-01
       */
      lastDonationDate?: string;
    };
    DonorImpact: {
      /** @example 5 */
      totalDonations: number;
      /** @example 15 */
      livesImpacted: number;
      /** @example 2 */
      emergenciesHandled: number;
      /** @example 1 */
      newDonorsRecruited: number;
    };
    Achievement: {
      /** @example ach_1 */
      id: string;
      /** @example First Donation */
      name: string;
      /** @example You donated for the first time! */
      description: string;
      /** @example badge_icon_url */
      badge: string;
      /**
       * Format: date-time
       * @example 2024-01-01
       */
      unlockedAt: string;
      /** @example 1 */
      level: number;
      /** @example 1 */
      streakDays: number;
    };
    DonationRequest: {
      /** @example req_123 */
      id: string;
      /**
       * @example A+
       * @enum {string}
       */
      bloodType: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      /**
       * @example URGENT
       * @enum {string}
       */
      priority: "CRITICAL" | "URGENT" | "SCHEDULED";
      /** @example 2 */
      unitsNeeded: number;
      /** @example Mercy Hospital */
      hospitalName: string;
      /** @example 123 Health St, Lagos */
      address: string;
      /** @example +2348012345678 */
      contactPhone: string;
      /** @example Go to emergency ward */
      instructions: string;
      /**
       * Format: date-time
       * @example 2024-02-21T08:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-02-21T09:00:00Z
       */
      acceptedAt?: string;
      /**
       * Format: date-time
       * @example 2024-02-21T09:30:00Z
       */
      rejectedAt?: string;
      /**
       * @example ACCEPTED
       * @enum {string}
       */
      status: "ACCEPTED" | "ON_YOUR_WAY" | "ARRIVED_AT_HOSPITAL" | "DONATION_COMPLETE" | "CANCELLED";
      /** @example 5.2 */
      distance: number;
    };
    DonationHistory: {
      /** @example hist_123 */
      id: string;
      /** @example City Hospital */
      hospitalName: string;
      /** @example A+ */
      bloodType: string;
      /** @example 1 */
      unitsGiven: number;
      /**
       * Format: date-time
       * @example 2024-01-15T10:00:00Z
       */
      donatedAt: string;
      /** @example DONATED */
      status: string;
      /** @example Mercy Clinic */
      facilityName: string;
      /** @example 123 Clinic Rd */
      facilityAddress?: string;
      /** @example +2348000000000 */
      facilityPhone?: string;
      /** @example Smooth experience */
      donorFeedback?: string;
    };
    CommunityActivity: {
      /** @example act_1 */
      id: string;
      /** @example John donated A+ blood */
      message: string;
      /** @example John Doe */
      actorName: string;
      /**
       * Format: date-time
       * @example 2024-02-21T10:00:00Z
       */
      timestamp: string;
      /** @example blood_drop */
      icon: string;
    };
    DonorDashboard: {
      /** @example Welcome back, John! */
      welcomeMessage: string;
      profileCompletion: components["schemas"]["ProfileCompletion"];
      donorStatus: components["schemas"]["DonorStatus"];
      impact: components["schemas"]["DonorImpact"];
      achievements: components["schemas"]["Achievement"][];
      nearbyBloodRequests: components["schemas"]["DonationRequest"][];
      donationHistory: components["schemas"]["DonationHistory"][];
      communityActivity: components["schemas"]["CommunityActivity"][];
    };
    DonorProfile: {
      /** @example donor_123 */
      id: string;
      /** @example John Doe */
      fullName: string;
      /** @example john@example.com */
      email: string;
      /** @example +2348012345678 */
      phoneNumber: string;
      /** @example A+ */
      bloodGroup: string;
      /** @example AA */
      genotype?: string;
      /** @example Male */
      gender: string;
      /** @example 6.5244 */
      latitude: number;
      /** @example 3.3792 */
      longitude: number;
      /** @example Lagos, Nigeria */
      location?: string;
      /** @example 123 Street Name */
      address?: string;
      /** @example Lagos */
      city?: string;
      /** @example Lagos State */
      state?: string;
      /** @example Nigeria */
      country?: string;
      /**
       * Format: date-time
       * @example 2023-10-01
       */
      lastDonationDate?: string;
      /** @example true */
      isAvailable: boolean;
      /** @example Jane Doe */
      emergencyContact?: string;
      /** @example +2348098765432 */
      emergencyContactPhone?: string;
      /**
       * Format: date-time
       * @example 2024-01-01
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2024-01-01
       */
      updatedAt: string;
    };
    Resource: {
      /** @example res_123 */
      id: string;
      /** @example How to prepare for your first donation */
      title: string;
      /** @example A comprehensive guide for new donors. */
      description: string;
      /**
       * @example ARTICLES
       * @enum {string}
       */
      category: "ALL" | "LATEST_NEWS" | "ARTICLES" | "COURSES" | "EXPLAINER_VIDEOS" | "RESEARCH";
      /** @example https://example.com/image.jpg */
      imageUrl: string;
      /** @example 5 mins */
      duration?: string;
      /** @example Read More */
      actionText: string;
      /** @example https://example.com/article */
      actionUrl: string;
      /** @example true */
      isFeatured: boolean;
      /**
       * Format: date-time
       * @example 2024-02-21T10:00:00Z
       */
      createdAt: string;
    };
    ResourcesPage: {
      resources: components["schemas"]["Resource"][];
      /** @example 45 */
      totalCount: number;
      /**
       * @example [
       *   "LATEST_NEWS",
       *   "ARTICLES"
       * ]
       */
      categories: string[];
    };
    NotificationPreference: {
      /** @example pref_123 */
      id: string;
      /** @example user_123 */
      userId: string;
      /** @example true */
      emergencyAlerts: boolean;
      /** @example true */
      donationReminders: boolean;
      /** @example false */
      communityUpdates: boolean;
      /** @example daily */
      reminderFrequency: string;
      /**
       * Format: date-time
       * @example 2024-01-01
       */
      updatedAt: string;
    };
    MedicalEligibility: {
      /** @example true */
      isEligible: boolean;
      /**
       * Format: date-time
       * @example 2024-04-01
       */
      nextEligibleDate: string;
      /** @example Too soon after last donation */
      reason?: string;
      /** @example 30 */
      daysSinceLastDonation: number;
      /** @example 60 */
      daysUntilEligible: number;
    };
    UpdateProfileInput: {
      /** @example John Doe */
      fullName?: string;
      /** @example +2348012345678 */
      phoneNumber?: string;
      /**
       * @example O+
       * @enum {string}
       */
      bloodGroup?: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      /**
       * @example AA
       * @enum {string}
       */
      genotype?: "AA" | "AS" | "SS" | "AC" | "SC";
      /**
       * @example Male
       * @enum {string}
       */
      gender?: "Male" | "Female" | "Other";
      /** @example 6.5244 */
      latitude?: number;
      /** @example 3.3792 */
      longitude?: number;
      /** @example Lagos, Nigeria */
      location?: string;
      /** @example 123 Street Name */
      address?: string;
      /** @example Lagos */
      city?: string;
      /** @example Lagos State */
      state?: string;
      /** @example Nigeria */
      country?: string;
      /** @example 2023-10-01 */
      lastDonationDate?: string;
      /** @example true */
      isAvailable?: boolean;
      /** @example Jane Doe */
      emergencyContact?: string;
      /** @example +2348098765432 */
      emergencyContactPhone?: string;
    };
    UpdateAvailabilityInput: {
      /**
       * @description 'Available', 'Busy', 'Unavailable'
       * @example Available
       */
      status: string;
    };
    UpdateNotificationPreferencesInput: {
      /** @example true */
      emergencyAlerts?: boolean;
      /** @example true */
      donationReminders?: boolean;
      /** @example false */
      communityUpdates?: boolean;
      /** @example daily */
      reminderFrequency?: string;
    };
    AcceptRequestInput: {
      /** @example req_123 */
      requestId: string;
      /** @example 6.5244 */
      latitude?: number;
      /** @example 3.3792 */
      longitude?: number;
    };
    DonationProgressUpdate: {
      /** @example req_123 */
      requestId: string;
      /**
       * @example ACCEPTED
       * @enum {string}
       */
      status: "ACCEPTED" | "ON_YOUR_WAY" | "ARRIVED_AT_HOSPITAL" | "DONATION_COMPLETE" | "CANCELLED";
      /**
       * Format: date-time
       * @example 2024-02-21T10:00:00Z
       */
      timestamp: string;
      /** @example Hospital Main Entrance */
      location?: string;
      /** @example 30 minutes */
      estimatedArrivalTime?: string;
    };
    RejectRequestInput: {
      /** @example req_123 */
      requestId: string;
      /** @example Too far away */
      reason?: string;
    };
    UpdateProgressInput: {
      /** @example req_123 */
      requestId: string;
      /**
       * @example ACCEPTED
       * @enum {string}
       */
      status: "ACCEPTED" | "ON_YOUR_WAY" | "ARRIVED_AT_HOSPITAL" | "DONATION_COMPLETE" | "CANCELLED";
      /** @example At hospital */
      location?: string;
      /** @example 15 mins */
      estimatedArrivalTime?: string;
    };
    SubmitHealthScreeningDto: {
      /**
       * @example {
       *   "feelingWell": true,
       *   "takenAntibiotics": false
       * }
       */
      answers: Record<string, never>;
    };
    SetGoalDto: {
      /** @example 4 */
      target: number;
      /** @example 2024 */
      year: number;
    };
    SubmitFeedbackInput: {
      /** @example req_123 */
      requestId: string;
      /**
       * @example AMAZING
       * @enum {string}
       */
      rating: "TERRIBLE" | "BAD" | "OKAY" | "GOOD" | "AMAZING";
      /** @example Great experience! */
      comments?: string;
    };
    DonationFeedback: {
      /** @example fb_123 */
      id: string;
      /** @example req_123 */
      requestId: string;
      /**
       * @example GOOD
       * @enum {string}
       */
      rating: "TERRIBLE" | "BAD" | "OKAY" | "GOOD" | "AMAZING";
      /** @example Great donor, very patient. */
      comments?: string;
      /**
       * Format: date-time
       * @example 2024-02-21T10:00:00Z
       */
      submittedAt: string;
    };
    SearchDonorsFilterDto: {
      /** @example A+ */
      bloodType?: string;
      /** @example 50 */
      radiusKm?: number;
      /** @example AVAILABLE */
      availability?: string;
      /** @example 0 */
      skip?: number;
      /** @example 10 */
      limit?: number;
      /**
       * @example [
       *   6.5244,
       *   3.3792
       * ]
       */
      coordinates?: string[];
    };
    BroadcastMessageDto: {
      /** @example req_123 */
      requestId: string;
      /** @example Lagos pulse leaders: We need A+ blood at Mercy Hospital urgently! */
      messageContent: string;
      /**
       * @example [
       *   "donor_1",
       *   "donor_2"
       * ]
       */
      recipientDonorIds?: string[];
      /** @example A+ */
      bloodType?: string;
      /**
       * @example [
       *   6.5244,
       *   3.3792
       * ]
       */
      coordinates?: number[];
      /** @example 10 */
      radiusKm?: number;
      /** @example BOTH */
      broadcastMethod?: string;
    };
    CreateCampaignDto: {
      title: string;
      description: string;
      startDate: string;
      endDate: string;
      targetDonations: number;
    };
    AdjustInventoryDto: {
      /** @enum {string} */
      bloodType: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      /** @enum {string} */
      type: "RECEIVED" | "USED" | "WASTED" | "MANUAL_ADJUSTMENT";
      units: number;
      reason?: string;
    };
    TransferInventoryDto: {
      toFacility: string;
      /** @enum {string} */
      bloodType: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
      units: number;
    };
    BookAppointmentDto: {
      facilityName: string;
      date: string;
      timeSlot: string;
    };
    EmergencyAlertDto: {
      targetBloodGroups: ("O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-")[];
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AuthController_signup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_verifyEmail: {
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_forgotPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_resetPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_refreshToken: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_getMe: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  AuthController_resendVerification: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendVerificationDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  UserController_me: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  UserController_updateProfile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserProfileDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  UserController_getUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  UserController_changePassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OnboardingController_initializeOnboarding: {
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  OnboardingController_submitStep1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OnboardingStep1Dto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  OnboardingController_submitStep2: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OnboardingStep2Dto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  OnboardingController_completeOnboarding: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteOnboardingDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  OnboardingController_getOnboardingStatus: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_createBloodRequest: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBloodRequestDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_getActiveRequests: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  BloodRequestController_getAllRequests: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  BloodRequestController_getMyRequests: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  BloodRequestController_getRequestsForDonor: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  BloodRequestController_getRequestById: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_acceptBloodRequest: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_confirmDonation: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_notifyDonorArrival: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  BloodRequestController_escalateRequest: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_updateBloodRequest: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBloodRequestDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  BloodRequestController_cancelBloodRequest: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Get user notification settings */
  NotificationController_getPreferences: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Update notification preferences */
  NotificationController_updatePreferences: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateNotificationPreferencesDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Get user's notification history (paginated) */
  NotificationController_getHistory: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Mark a specific notification as read */
  NotificationController_markRead: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Mark all notifications as read */
  NotificationController_markAllRead: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AnalyticsController_getBridgerAnalytics: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AnalyticsController_getAnalytics: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  RoleUpgradeController_requestRoleUpgrade: {
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  RoleUpgradeController_getPendingUpgradeRequests: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  RoleUpgradeController_approveRoleUpgrade: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  RoleUpgradeController_rejectRoleUpgrade: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  RoleUpgradeController_getMyUpgradeHistory: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  DonorController_getDonorDashboard: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DonorDashboard"];
        };
      };
    };
  };
  DonorController_getDonorDashboardSummary: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getDonorStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getDonorProfileCompletion: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  DonorController_getDonorProfile: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DonorProfile"];
        };
      };
    };
  };
  DonorController_updateProfile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DonorProfile"];
        };
      };
    };
  };
  DonorController_getNearbyBloodRequests: {
    parameters: {
      query: {
        radiusKm: string;
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getBloodRequestDetails: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DonationRequest"];
        };
      };
    };
  };
  DonorController_getResources: {
    parameters: {
      query: {
        category: string;
        search: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ResourcesPage"];
        };
      };
    };
  };
  DonorController_getDonationHistory: {
    parameters: {
      query: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
        status: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getDonationRecord: {
    parameters: {
      path: {
        donationId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  DonorController_getDonationCertificate: {
    parameters: {
      path: {
        donationId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getNotificationPreferences: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NotificationPreference"];
        };
      };
    };
  };
  DonorController_updateNotificationPreferences: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateNotificationPreferencesInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["NotificationPreference"];
        };
      };
    };
  };
  DonorController_getMedicalEligibility: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MedicalEligibility"];
        };
      };
    };
  };
  DonorController_updateAvailability: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAvailabilityInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DonorProfile"];
        };
      };
    };
  };
  DonorController_acceptBloodRequest: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptRequestInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DonationProgressUpdate"];
        };
      };
    };
  };
  DonorController_rejectBloodRequest: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectRequestInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": boolean;
        };
      };
    };
  };
  DonorController_updateDonationProgress: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProgressInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DonationProgressUpdate"];
        };
      };
    };
  };
  DonorController_getRequestProgress: {
    parameters: {
      path: {
        requestId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  DonorController_getBadges: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getLeaderboard: {
    parameters: {
      query: {
        limit: string;
        region: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_toggleAnonymity: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getHealthScreeningQuestions: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_submitHealthScreening: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitHealthScreeningDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DonorController_getGoal: {
    parameters: {
      query: {
        year: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  DonorController_setGoal: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetGoalDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  DonorController_getShareableImpact: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_getActivityFeed: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DonorController_submitDonationFeedback: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitFeedbackInput"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DonationFeedback"];
        };
      };
    };
  };
  PulseLeaderController_getPulseLeaderDashboard: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PulseLeaderController_searchDonors: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchDonorsFilterDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PulseLeaderController_getEscalationHistory: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PulseLeaderController_broadcastMessage: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BroadcastMessageDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PulseLeaderController_getRecentActivities: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PulseLeaderController_getNetworkPerformance: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PulseLeaderController_getCampaigns: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PulseLeaderController_createCampaign: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCampaignDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  PulseLeaderController_getBridgers: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PulseLeaderController_addBridgerToOrg: {
    parameters: {
      path: {
        bridgerId: string;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Get current blood unit counts per type at user's facility */
  InventoryController_getInventory: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** Submit adjustment (received/used/wastage) with reason */
  InventoryController_adjustInventory: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdjustInventoryDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Adjustment history (paginated) */
  InventoryController_getInventoryHistory: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Inventory adjustment audit trail */
  InventoryController_getInventoryAudit: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Transfer units between facilities */
  InventoryController_transferInventory: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferInventoryDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Transfer history */
  InventoryController_getTransferHistory: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Get my appointments */
  AppointmentController_getMyAppointments: {
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>[];
        };
      };
    };
  };
  /** Book a donation appointment */
  AppointmentController_bookAppointment: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookAppointmentDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Reschedule an appointment */
  AppointmentController_rescheduleAppointment: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Cancel an appointment */
  AppointmentController_cancelAppointment: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Get Bridger dashboard statistics */
  BridgerController_getDashboardStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Search for available donors */
  BridgerController_searchDonors: {
    parameters: {
      query: {
        bloodType: string;
        state: string;
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Get facility appointments */
  BridgerController_getAppointments: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Send emergency push notification to donors */
  BridgerController_sendEmergencyAlert: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmergencyAlertDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
}
